# Generated by Django 4.2.2 on 2023-06-16 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
