# Generated by Django 4.2.2 on 2023-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (0, 'Rejected'), (2, 'Pending')]),
        ),
    ]
