# Generated by Django 4.2.2 on 2023-06-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='vacancies',
            field=models.IntegerField(null=True),
        ),
    ]
