# Generated by Django 4.2.2 on 2023-06-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0002_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='grade',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
