# Generated by Django 4.2.2 on 2023-06-13 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0003_alter_interview_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (0, 'Rejected'), (2, 'Pending')], default=2),
        ),
        migrations.AlterField(
            model_name='interview',
            name='grade',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
