# Generated by Django 4.2.2 on 2023-06-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0003_alter_applicant_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='user',
            new_name='interviewer',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
