# Generated by Django 4.2.2 on 2023-06-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0004_alter_tenant_name'),
        ('Tenant', '0006_alter_applicant_company_alter_interview_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Landlord.tenant'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Landlord.tenant'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Landlord.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Landlord.tenant'),
        ),
    ]
