# Generated by Django 4.2.2 on 2023-06-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0003_alter_position_name'),
        ('Tenant', '0009_alter_applicant_resume'),
    ]

    operations = [
    ]
