# Generated by Django 4.2.2 on 2023-06-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0009_merge_0006_tenant_image_0008_subscription_pr_id'),
        ('Tenant', '0010_merge_20230620_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='room',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Landlord.tenant'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Landlord.tenant'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Landlord.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Landlord.tenant'),
        ),
    ]
