# Generated by Django 4.2.2 on 2023-06-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0014_alter_applicant_company_alter_interview_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
