# Generated by Django 4.2.2 on 2023-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0015_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='room',
            field=models.CharField(blank=True, default='company'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='url',
            field=models.CharField(default='http://localhost:8000/meeting'),
        ),
    ]
