# Generated by Django 4.2.2 on 2023-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0016_alter_interview_room_alter_interview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
