# Generated by Django 4.2.2 on 2023-06-21 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0017_alter_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.IntegerField(choices=[(3, 'Accepted'), (0, 'Rejected'), (2, 'Pending'), (1, 'Candidate')], default=2),
        ),
        migrations.AlterField(
            model_name='interview',
            name='room',
            field=models.UUIDField(blank=True, default=uuid.UUID),
        ),
    ]
