# Generated by Django 4.2.2 on 2023-06-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0018_alter_applicant_status_alter_interview_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='room',
            field=models.CharField(blank=True),
        ),
    ]
