# Generated by Django 4.2.2 on 2023-06-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0010_merge_20230619_0052'),
        ('Tenant', '0020_applicant_hasinterview'),
    ]

    operations = [
    ]
