# Generated by Django 4.2.2 on 2023-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='room_name',
            field=models.CharField(max_length=500),
        ),
    ]
