<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-13 18:05
=======
# Generated by Django 4.2.2 on 2023-06-13 17:51
>>>>>>> ef5ca40331993ec1c647d8e0d71d4da5a8be8fd7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('annual_price', models.FloatField()),
                ('monthly_price', models.FloatField()),
<<<<<<< HEAD
                ('description', models.TextField(max_length=128)),
=======
                ('description', models.TextField(default='', max_length=128)),
>>>>>>> ef5ca40331993ec1c647d8e0d71d4da5a8be8fd7
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('free_trial', models.BooleanField()),
                ('database', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Landlord.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
