# Generated by Django 4.2.2 on 2023-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.IntegerField(choices=[(1, 'free'), (2, 'gold'), (3, 'plantium')]),
        ),
        migrations.DeleteModel(
            name='SubscriptionName',
        ),
    ]
