# Generated by Django 4.2.2 on 2023-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0002_alter_subscription_name_delete_subscriptionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('free', 'free'), ('gold', 'gold'), ('plantium', 'plantium')]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Monthly', 'Monthly')]),
        ),
    ]
