# Generated by Django 4.2.2 on 2023-06-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0005_alter_tenant_expiration_date_alter_tenant_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='users_no',
            field=models.IntegerField(default=100),
        ),
    ]
