# Generated by Django 4.2.2 on 2023-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0005_alter_tenant_expiration_date_alter_tenant_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
