# Generated by Django 4.2.2 on 2023-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0007_alter_subscription_name_alter_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pr_id',
            field=models.CharField(default=''),
        ),
    ]
