# Generated by Django 4.2.2 on 2023-06-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0006_tenant_image'),
        ('Landlord', '0008_subscription_pr_id'),
    ]

    operations = [
    ]
